sudo: required
services:
  - docker

before_install:
  - docker build -t ldawit/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ldawit/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-011908850102"
  bucket_path: "docker-react-2"
  On:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY