sudo: required
services:
  - docker

before_install:
  - docker build -t ldawit/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ldawit/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "docker409"
  bucket_path: "docker"
  edge: true
  On:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

